# Generated by Django 5.2.1 on 2025-05-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_game_cover_image_gamephoto_gamevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamevideo',
            name='game',
        ),
        migrations.AddField(
            model_name='teammember',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='trailer_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
        migrations.CreateModel(
            name='DevlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='Enter a YouTube embed URL (e.g., https://www.youtube.com/embed/...)', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Brief description of the development part')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devlog_video_entries', to='studio.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='devlog_videos',
            field=models.ManyToManyField(blank=True, related_name='related_games_devlogs', to='studio.devlogvideo'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='studio.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='game_entries', to='studio.photo'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='Enter a YouTube embed URL (e.g., https://www.youtube.com/embed/...)', max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_set', to='studio.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='game_entries_videos', to='studio.video'),
        ),
        migrations.DeleteModel(
            name='GamePhoto',
        ),
        migrations.DeleteModel(
            name='GameVideo',
        ),
    ]
