# Generated by Django 5.2.1 on 2025-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_remove_gamevideo_game_teammember_social_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Designates whether this game is featured on the home page.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='devlog_videos',
            field=models.ManyToManyField(blank=True, related_name='games', to='studio.devlogvideo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='games', to='studio.photo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='games', to='studio.video'),
        ),
    ]
