# Generated by Django 5.2.1 on 2025-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_game_is_featured_alter_game_devlog_videos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='game',
            name='devlog_videos',
        ),
        migrations.AddField(
            model_name='devlogvideo',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devlogvideo',
            name='content',
            field=models.TextField(default='Unknown Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devlogvideo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devlogvideo',
            name='video_url',
            field=models.URLField(),
        ),
    ]
