# Generated by Django 5.2.1 on 2025-07-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_goals/')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze Supporter'), ('silver', 'Silver Supporter'), ('gold', 'Gold Supporter'), ('platinum', 'Platinum Supporter'), ('diamond', 'Diamond Supporter')], max_length=20, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('perks', models.TextField(help_text='List of perks for this tier, one per line')),
                ('icon', models.CharField(default='fas fa-heart', help_text='FontAwesome icon class', max_length=50)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('one_time', 'One-time Donation'), ('monthly', 'Monthly Recurring'), ('yearly', 'Yearly Recurring')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='thank_you_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.donationgoal'),
        ),
        migrations.AddField(
            model_name='donation',
            name='sponsor_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.sponsortier'),
        ),
    ]
