# Generated by Django 5.2.1 on 2025-07-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_achievementcategory_userprofile_custom_title_and_more'),
    ]

    operations = [
    ]
