# Generated by Django 5.2.1 on 2025-07-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_alter_game_created_at_comment_communitygamereview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancedgamerating',
            old_name='difficulty',
            new_name='innovation',
        ),
    ]
